services:
  recipe-app:
    build: .
    image: recipe-app
    container_name: recipe-app
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      - IngredientsFile=/app/data/ingredients.json
      - RecipesFile=/app/data/recipes.json
    volumes:
      - recipe-data:/app/data

volumes:
  recipe-data:
    name: recipe-data
